import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Cambiado a Poppins
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

// Configuración de la fuente Poppins
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}> {/* Cambiado a poppins.className */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
